package gui

import (
	rl "github.com/gen2brain/raylib-go/raylib"
)

type ScanCode = int32

var runeToKey = map[rune]ScanCode{
	'0': rl.KeyZero,
	'1': rl.KeyOne,
	'2': rl.KeyTwo,
	'3': rl.KeyThree,
	'4': rl.KeyFour,
	'5': rl.KeyFive,
	'6': rl.KeySix,
	'7': rl.KeySeven,
	'8': rl.KeyEight,
	'9': rl.KeyNine,

	'a': rl.KeyA,
	'b': rl.KeyB,
	'c': rl.KeyC,
	'd': rl.KeyD,
	'e': rl.KeyE,
	'f': rl.KeyF,
	'g': rl.KeyG,
	'h': rl.KeyH,
	'i': rl.KeyI,
	'j': rl.KeyJ,
	'k': rl.KeyK,
	'l': rl.KeyL,
	'm': rl.KeyM,
	'n': rl.KeyN,
	'o': rl.KeyO,
	'p': rl.KeyP,
	'q': rl.KeyQ,
	'r': rl.KeyR,
	's': rl.KeyS,
	't': rl.KeyT,
	'u': rl.KeyU,
	'v': rl.KeyV,
	'w': rl.KeyW,
	'x': rl.KeyX,
	'y': rl.KeyY,
	'z': rl.KeyZ,

	'A': rl.KeyA,
	'B': rl.KeyB,
	'C': rl.KeyC,
	'D': rl.KeyD,
	'E': rl.KeyE,
	'F': rl.KeyF,
	'G': rl.KeyG,
	'H': rl.KeyH,
	'I': rl.KeyI,
	'J': rl.KeyJ,
	'K': rl.KeyK,
	'L': rl.KeyL,
	'M': rl.KeyM,
	'N': rl.KeyN,
	'O': rl.KeyO,
	'P': rl.KeyP,
	'Q': rl.KeyQ,
	'R': rl.KeyR,
	'S': rl.KeyS,
	'T': rl.KeyT,
	'U': rl.KeyU,
	'V': rl.KeyV,
	'W': rl.KeyW,
	'X': rl.KeyX,
	'Y': rl.KeyY,
	'Z': rl.KeyZ,
}
